# These are supported funding model platforms
# Replace placeholder usernames with your actual accounts

ko_fi: earthcraft
# buy_me_a_coffee: slavkostojnic
# github: aRcHmaGe333
# custom: ["https://paypal.me/slavkostojnic"]
